spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lms
    password: 1407
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true